/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import model.model_khachhang;
import service.repositories_khachhang;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tranl
 */
public class KhachHang_Views extends javax.swing.JPanel {

    DefaultTableModel defaultTableModel = new DefaultTableModel();
    private repositories_khachhang server = new repositories_khachhang();
    private model_khachhang khachhang = new model_khachhang();

    /**
     * Creates new form KhachHang_Views
     */
    public KhachHang_Views() {
        initComponents();
//        setLocationRelativeTo(null);
        this.hienthi();
    }

    public void hienthi() {
        defaultTableModel = (DefaultTableModel) tblisst.getModel();
        defaultTableModel.setRowCount(0);
        List<model_khachhang> khachhang = repositories_khachhang.getKhachHang();
        for (model_khachhang kh : khachhang) {
            defaultTableModel.addRow(new Object[]{kh.getMaKH(), kh.getTenKh(), kh.getGioiTinh(), kh.getDiaChi(), kh.getSDT(), kh.getLoaiKhacHang(), kh.getDiemThanhVien()});

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtkhachang = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_sodt = new javax.swing.JTextField();
        txt_diachi = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_tenkh = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_diemthanhvien = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_loaikhachhang = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btn_them = new javax.swing.JButton();
        btn_sua = new javax.swing.JButton();
        btn_xoa = new javax.swing.JButton();
        btn_xoa1 = new javax.swing.JButton();
        rdo_nam = new javax.swing.JRadioButton();
        rdo_nu = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblisst = new javax.swing.JTable();
        txtTimKiem = new javax.swing.JTextField();
        BtnTimKiem = new javax.swing.JButton();

        setBackground(new java.awt.Color(251, 227, 203));
        setPreferredSize(new java.awt.Dimension(1061, 650));

        jPanel2.setBackground(new java.awt.Color(251, 227, 203));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin khách hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel2.setText("Mã khách hàng:");

        txtkhachang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkhachangActionPerformed(evt);
            }
        });

        jLabel3.setText("Số điện thoại:");

        txt_sodt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_sodtActionPerformed(evt);
            }
        });

        txt_diachi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_diachiActionPerformed(evt);
            }
        });

        jLabel5.setText("Địa chỉ:");

        jLabel4.setText("Tên khách hàng:");

        txt_tenkh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tenkhActionPerformed(evt);
            }
        });

        jLabel7.setText("Điểm thành viên:");

        txt_diemthanhvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_diemthanhvienActionPerformed(evt);
            }
        });

        jLabel6.setText("Loại khách hàng:");

        txt_loaikhachhang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_loaikhachhangActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(251, 227, 203));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btn_them.setBackground(new java.awt.Color(0, 204, 51));
        btn_them.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_them.setText("Thêm thông tin");
        btn_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themActionPerformed(evt);
            }
        });

        btn_sua.setBackground(new java.awt.Color(0, 204, 51));
        btn_sua.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_sua.setText("Sửa thông tin");
        btn_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suaActionPerformed(evt);
            }
        });

        btn_xoa.setBackground(new java.awt.Color(0, 204, 51));
        btn_xoa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_xoa.setText("Xoá thông tin");
        btn_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaActionPerformed(evt);
            }
        });

        btn_xoa1.setBackground(new java.awt.Color(0, 204, 51));
        btn_xoa1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_xoa1.setText("Làm Mới");
        btn_xoa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoa1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_xoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_them, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                    .addComponent(btn_sua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_xoa1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 15, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(btn_them)
                .addGap(18, 18, 18)
                .addComponent(btn_sua)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_xoa)
                .addGap(18, 18, 18)
                .addComponent(btn_xoa1)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        buttonGroup1.add(rdo_nam);
        rdo_nam.setText("Nam");

        buttonGroup1.add(rdo_nu);
        rdo_nu.setText("nữ");
        rdo_nu.setToolTipText("");

        jLabel9.setText("Giới Tính");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtkhachang, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(rdo_nam)
                                        .addGap(92, 92, 92)
                                        .addComponent(rdo_nu))
                                    .addComponent(txt_tenkh, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                                .addComponent(txt_loaikhachhang, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_sodt, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                            .addComponent(txt_diachi)
                            .addComponent(txt_diemthanhvien))
                        .addGap(101, 101, 101))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtkhachang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(txt_sodt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_diachi, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(txt_tenkh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(rdo_nam)
                                    .addComponent(rdo_nu))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(txt_loaikhachhang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)
                                    .addComponent(txt_diemthanhvien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(251, 227, 203));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "THÊM THÔNG TIN KHÁCH HÀNG", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N

        tblisst.setAutoCreateRowSorter(true);
        tblisst.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "mã khách hàng", "Tên khách hàng", "Giới tính", "Địa chỉ", "Số điện thoại", "Loại khách hàng", "Điểm thành viên"
            }
        ));
        tblisst.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblisstMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblisst);

        BtnTimKiem.setBackground(new java.awt.Color(0, 204, 51));
        BtnTimKiem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnTimKiem.setText("Tìm kiếm");
        BtnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTimKiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(326, Short.MAX_VALUE)
                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(BtnTimKiem)
                .addGap(324, 324, 324))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnTimKiem)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtkhachangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkhachangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtkhachangActionPerformed

    private void txt_sodtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_sodtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_sodtActionPerformed

    private void txt_diachiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_diachiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_diachiActionPerformed

    private void txt_tenkhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tenkhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tenkhActionPerformed

    private void txt_diemthanhvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_diemthanhvienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_diemthanhvienActionPerformed

    private void txt_loaikhachhangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_loaikhachhangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_loaikhachhangActionPerformed

    private void btn_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themActionPerformed
        // TODO add your handling code here:
        String ma = txtkhachang.getText().trim();
        String ten = txt_tenkh.getText().trim();
        String GioString = rdo_nam.isSelected() ? "Nam" : "Nữ";
        String diachi = txt_diachi.getText().trim();
        String sdtStr = txt_sodt.getText().trim();
        String loaikhachhang = txt_loaikhachhang.getText().trim();
        String diemThanhVienStr = txt_diemthanhvien.getText().trim();

        if (ma.isEmpty() || ten.isEmpty() || diachi.isEmpty() || sdtStr.isEmpty() || loaikhachhang.isEmpty() || diemThanhVienStr.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Vui lòng điền đầy đủ thông tin!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (!sdtStr.matches("\\d+")) {
            JOptionPane.showMessageDialog(null, "Số điện thoại chỉ được phép chứa các ký tự số!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int DiemThanhVien;
        try {

            DiemThanhVien = Integer.parseInt(diemThanhVienStr);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Số điện thoại và điểm thành viên phải là số!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (server.exitByMa(ma)) {
            JOptionPane.showMessageDialog(this, "Mã bị Trùng ! Vui lòng đổi mã khác");
            return;
        }
        int confirm = JOptionPane.showConfirmDialog(null, "Bạn có chắc chắn muốn thêm khách hàng này không?", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }
        model_khachhang kh = new model_khachhang(ma, ten, GioString, diachi, sdtStr, loaikhachhang, DiemThanhVien);
        repositories_khachhang.them(kh);
        JOptionPane.showMessageDialog(null, "Thêm khách hàng thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        hienthi();

    }//GEN-LAST:event_btn_themActionPerformed

    private void btn_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suaActionPerformed
        // TODO add your handling code here:
        String ma = txtkhachang.getText().trim();
        String ten = txt_tenkh.getText().trim();
        String GioTinh = rdo_nam.isSelected() ? "Nam" : "Nữ";
        String diachi = txt_diachi.getText().trim();
        String sdtStr = txt_sodt.getText().trim();
        String loaikhachhang = txt_loaikhachhang.getText().trim();
        String diemThanhVienStr = txt_diemthanhvien.getText().trim();

        if (ma.isEmpty() || ten.isEmpty() || diachi.isEmpty() || sdtStr.isEmpty() || loaikhachhang.isEmpty() || diemThanhVienStr.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Vui lòng điền đầy đủ thông tin!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (!sdtStr.matches("\\d+")) {
            JOptionPane.showMessageDialog(null, "Số điện thoại chỉ được phép chứa các ký tự số!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int DiemThanhVien;
        try {

            DiemThanhVien = Integer.parseInt(diemThanhVienStr);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "điểm thành viên phải là số!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(null, "Bạn có chắc chắn muốn sửa thông tin khách hàng này không?", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }

        model_khachhang kh = new model_khachhang(ma, ten, GioTinh, diachi, sdtStr, loaikhachhang, DiemThanhVien);
        repositories_khachhang.update(kh);
        JOptionPane.showMessageDialog(null, "Đã Sửa thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);

        hienthi();

    }//GEN-LAST:event_btn_suaActionPerformed

    private void btn_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaActionPerformed
        
    }//GEN-LAST:event_btn_xoaActionPerformed

    private void btn_xoa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoa1ActionPerformed
        
    }//GEN-LAST:event_btn_xoa1ActionPerformed

    private void tblisstMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblisstMouseClicked
        // TODO add your handling code here:
        int index = tblisst.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) tblisst.getModel();
        txtkhachang.setText(model.getValueAt(index, 0).toString());
        txt_tenkh.setText(model.getValueAt(index, 1).toString());
        String GioiTinh = model.getValueAt(index, 2).toString();
        if (GioiTinh.equals("Nam")) {
            rdo_nam.setSelected(true);

        } else {
            rdo_nu.setSelected(true);
        }
        txt_diachi.setText(model.getValueAt(index, 3).toString());
        txt_sodt.setText(model.getValueAt(index, 4).toString());
        txt_loaikhachhang.setText(model.getValueAt(index, 5).toString());
        txt_diemthanhvien.setText(model.getValueAt(index, 6).toString());

    }//GEN-LAST:event_tblisstMouseClicked

    private void BtnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTimKiemActionPerformed
        

    }//GEN-LAST:event_BtnTimKiemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnTimKiem;
    private javax.swing.JButton btn_sua;
    private javax.swing.JButton btn_them;
    private javax.swing.JButton btn_xoa;
    private javax.swing.JButton btn_xoa1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdo_nam;
    private javax.swing.JRadioButton rdo_nu;
    private javax.swing.JTable tblisst;
    private javax.swing.JTextField txtTimKiem;
    private javax.swing.JTextField txt_diachi;
    private javax.swing.JTextField txt_diemthanhvien;
    private javax.swing.JTextField txt_loaikhachhang;
    private javax.swing.JTextField txt_sodt;
    private javax.swing.JTextField txt_tenkh;
    private javax.swing.JTextField txtkhachang;
    // End of variables declaration//GEN-END:variables
}
