/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import model.Model_Voucher;
import service.Repo_Voucher;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tranl
 */
public class Voucher_Views extends javax.swing.JPanel {

    private Repo_Voucher repo_Voucher = new Repo_Voucher();
    private DefaultTableModel dtm = new DefaultTableModel();
    private int i = -1;

    /**
     * Creates new form Voucher_Views
     */
    public Voucher_Views() {
        initComponents();
        this.fillTable(repo_Voucher.getAll());
    }

    void fillTable(ArrayList<Model_Voucher> list) {
        dtm = (DefaultTableModel) tblQLVoucher.getModel();
        dtm.setRowCount(0);
        for (Model_Voucher x : list) {
            dtm.addRow(x.toDaTaRow());
        }
    }

    void clearForm() {
        txtmavoucher.setText("");
        txttenvoucher.setText("");
        cbbhinhthuc.setSelectedItem("Giảm Tiền");
        txtsotiengiam.setText("");
        txtsoptgiam.setText("");
        Jdatengaybd.setDate(new Date());
        jdatengaykt.setDate(new Date());
        rdoconhieuluc.setSelected(true);
        txtdkgiam.setText("");
        txtmucgiamtoida.setText("");
    }

    void showData(int i) {
        String maVoucher = tblQLVoucher.getValueAt(i, 0).toString();
        String tenVoucher = tblQLVoucher.getValueAt(i, 1).toString();
        String hinhThuc = tblQLVoucher.getValueAt(i, 2).toString();
        String soTienGiam = tblQLVoucher.getValueAt(i, 3).toString();
        String soptGiam = tblQLVoucher.getValueAt(i, 4).toString();
        String ngayBatDau = tblQLVoucher.getValueAt(i, 5).toString();
        String ngayKetThuc = tblQLVoucher.getValueAt(i, 6).toString();
        String trangThai = tblQLVoucher.getValueAt(i, 7).toString();
        String dkGiam = tblQLVoucher.getValueAt(i, 8).toString();
        String mucGiamToiDastr = tblQLVoucher.getValueAt(i, 9).toString();
        

        txtmavoucher.setText(maVoucher);
        txttenvoucher.setText(tenVoucher);
        txtsotiengiam.setText(soTienGiam);
        txtsoptgiam.setText(soptGiam);
        txtdkgiam.setText(dkGiam);
        txtmucgiamtoida.setText(mucGiamToiDastr);
        if(hinhThuc.equals("Giảm Tiền")){
            cbbhinhthuc.setSelectedItem("Giảm Tiền");
            txtsoptgiam.setEnabled(false);
            txtsotiengiam.setEnabled(true);
        }else{
            cbbhinhthuc.setSelectedItem("Giảm %");
            txtsotiengiam.setEnabled(false);
            txtsoptgiam.setEnabled(true);
        }
        try {
            Jdatengaybd.setDate(new SimpleDateFormat("yyyy-MM-dd").parse(ngayBatDau));
            jdatengaykt.setDate(new SimpleDateFormat("yyyy-MM-dd").parse(ngayKetThuc));
        } catch (ParseException e) {
            e.printStackTrace();
        }

        if (trangThai.equals("Hoat Ðong")) {
            rdoconhieuluc.setSelected(true);
        } else {
            rdohethieuluc.setSelected(true);
        }
    }
        private void updateFieldsBasedOnComboBox() {
            String selected = cbbhinhthuc.getSelectedItem().toString();
            if (selected.equals("Giảm Tiền")) {
                txtsoptgiam.setEnabled(false);
                txtsotiengiam.setEnabled(true);
                txtsoptgiam.setText("0");
            } else if (selected.equals("Giảm %")) {
                txtsotiengiam.setEnabled(false);
                txtsoptgiam.setEnabled(true);
                txtsotiengiam.setText("0");
            }
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        btnthem = new javax.swing.JButton();
        btnsua = new javax.swing.JButton();
        btnxoa = new javax.swing.JButton();
        btnlammoi = new javax.swing.JButton();
        btnlammoitable = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblQLVoucher = new javax.swing.JTable();
        txttimkiem = new javax.swing.JTextField();
        btntimkiem = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtmavoucher = new javax.swing.JTextField();
        txttenvoucher = new javax.swing.JTextField();
        txtsotiengiam = new javax.swing.JTextField();
        rdoconhieuluc = new javax.swing.JRadioButton();
        rdohethieuluc = new javax.swing.JRadioButton();
        Jdatengaybd = new com.toedter.calendar.JDateChooser();
        jdatengaykt = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        cbbhinhthuc = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        txtsoptgiam = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtdkgiam = new javax.swing.JTextField();
        txtmucgiamtoida = new javax.swing.JTextField();

        setBackground(new java.awt.Color(251, 227, 203));
        setPreferredSize(new java.awt.Dimension(1184, 650));

        jPanel3.setBackground(new java.awt.Color(251, 227, 203));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chức năng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        btnthem.setBackground(new java.awt.Color(0, 204, 51));
        btnthem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnthem.setText("Thêm Voucher");
        btnthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemActionPerformed(evt);
            }
        });

        btnsua.setBackground(new java.awt.Color(0, 204, 51));
        btnsua.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnsua.setText("Sửa Voucher");
        btnsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuaActionPerformed(evt);
            }
        });

        btnxoa.setBackground(new java.awt.Color(0, 204, 51));
        btnxoa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnxoa.setText("Xóa Voucher");
        btnxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoaActionPerformed(evt);
            }
        });

        btnlammoi.setBackground(new java.awt.Color(0, 204, 51));
        btnlammoi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnlammoi.setText("Làm Mới");
        btnlammoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlammoiActionPerformed(evt);
            }
        });

        btnlammoitable.setBackground(new java.awt.Color(0, 204, 51));
        btnlammoitable.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnlammoitable.setText("Làm Mới Table");
        btnlammoitable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlammoitableActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnsua, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnxoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnthem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                    .addComponent(btnlammoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnlammoitable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(btnthem, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(btnsua, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnxoa, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnlammoi, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnlammoitable, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        jPanel4.setBackground(new java.awt.Color(251, 227, 203));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách voucher", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        tblQLVoucher.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã VouCher", "Tên VouCher", "Hình Thức", "Số Tiền Giảm", "Số % Giảm", "Ngày Bắt Đầu", "Ngày Kết Thúc", "Trạng Thái", "Điều Kiện Giảm", "Mức Giảm Tối Đa"
            }
        ));
        tblQLVoucher.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblQLVoucherMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblQLVoucher);

        btntimkiem.setBackground(new java.awt.Color(0, 204, 51));
        btntimkiem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btntimkiem.setText("Tìm Kiếm");
        btntimkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntimkiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txttimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btntimkiem)
                .addGap(335, 335, 335))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btntimkiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        jPanel1.setBackground(new java.awt.Color(251, 227, 203));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông Tin VouCher", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Mã Voucher");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Tên Voucher");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Số Tiền Giảm");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Ngày bắt đầu");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Ngày kết thúc");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Trạng Thái");

        txtmavoucher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmavoucherActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdoconhieuluc);
        rdoconhieuluc.setText("Hoat Đong");
        rdoconhieuluc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoconhieulucActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdohethieuluc);
        rdohethieuluc.setText("Khong Hoat Đong");

        Jdatengaybd.setDateFormatString("yyyy-MM-dd");

        jdatengaykt.setDateFormatString("yyyy-MM-dd");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Hình Thức");

        cbbhinhthuc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Giảm Tiền", "Giảm %" }));
        cbbhinhthuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbhinhthucActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Số % Giảm");

        jLabel9.setText("%");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Điều Kiện Giảm");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("Mức Giảm Tối Thiểu");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtmavoucher))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txttenvoucher))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtsotiengiam, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                                .addComponent(cbbhinhthuc, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtsoptgiam, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel9)))))
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE))
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rdoconhieuluc)
                        .addGap(18, 18, 18)
                        .addComponent(rdohethieuluc))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(Jdatengaybd, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                        .addComponent(jdatengaykt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtmucgiamtoida, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                        .addComponent(txtdkgiam, javax.swing.GroupLayout.Alignment.LEADING)))
                .addGap(0, 68, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel4)
                        .addComponent(txtmavoucher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Jdatengaybd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txttenvoucher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5))
                    .addComponent(jdatengaykt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(rdoconhieuluc)
                    .addComponent(rdohethieuluc)
                    .addComponent(jLabel7)
                    .addComponent(cbbhinhthuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtsotiengiam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txtdkgiam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtsoptgiam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11)
                    .addComponent(txtmucgiamtoida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemActionPerformed
        String maVoucher = txtmavoucher.getText().trim();
        String tenKM = txttenvoucher.getText().trim();
        String hinhThuc = cbbhinhthuc.getSelectedItem().toString();
        String soTienGiamstr = txtsotiengiam.getText().trim();
        String soptGiamstr = txtsoptgiam.getText().trim();
        Date ngaybd = Jdatengaybd.getDate();
        Date ngaykt = jdatengaykt.getDate();
        String dkGiam = txtdkgiam.getText().trim();
        String mucGiamToiDastr = txtmucgiamtoida.getText().trim();
        String trangThai;
        if (rdoconhieuluc.isSelected()) {
            trangThai = "Hoat Ðong";
        } else {
            trangThai = "Khong Hoat Đong";
        }
        if (maVoucher.isEmpty() || tenKM.isEmpty() || ngaybd == null || ngaykt == null || dkGiam.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đủ thông tin");
            return;
        }
        float soTienGiam;
        try {
            soTienGiam = Float.parseFloat(soTienGiamstr);
            if (soTienGiam <0) {
                JOptionPane.showMessageDialog(this, "Số tiền giảm phải lớn hơn hoặc bằng 0");
                return;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập số tiền giảm là số nguyên");
            return;
        }
        int soptGiam;
        try {
            soptGiam = Integer.parseInt(soptGiamstr);
            if(soptGiam<0){
                JOptionPane.showMessageDialog(this, "Số tiền giảm phải lớn hơn hoặc bằng 0");
                return;
            }if(soptGiam>100){
                JOptionPane.showMessageDialog(this,"Số % giảm phải nhỏ hơn hoặc bằng 100");
                return;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập số % giảm là số nguyên");
            return;
        }
        if (ngaybd.after(ngaykt)) {
            JOptionPane.showMessageDialog(this, "Ngày kết thúc phải sau ngày bắt đầu");
            return;
        }
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String strNgayBatDau = sdf.format(ngaybd);
        String strNgayKetThuc = sdf.format(ngaykt);
        float mucGiamToiDa;
        try {
            mucGiamToiDa= Float.parseFloat(mucGiamToiDastr);
            if(mucGiamToiDa<=0){
                JOptionPane.showMessageDialog(this, "Vui lòng nhập mức giảm tối đa là số nguyên");
                return;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập mức giảm tối đa là số nguyên");
            return;
        }
        if (repo_Voucher.exitByMa(maVoucher)) {
            JOptionPane.showMessageDialog(this, "Mã bị Trùng ! Vui lòng đổi mã khác");
            return;
        }
        int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn thêm?", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION) {
            return; // User chose not to proceed
        }
        Model_Voucher mv = new Model_Voucher(maVoucher, tenKM, hinhThuc, soTienGiam, soptGiam, ngaybd, ngaykt, trangThai,dkGiam, mucGiamToiDa);
        this.repo_Voucher.them(mv);
        this.fillTable(repo_Voucher.getAll());
        this.clearForm();
        JOptionPane.showMessageDialog(this, "Thêm thành công");
    }//GEN-LAST:event_btnthemActionPerformed

    private void btnsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuaActionPerformed
        i = tblQLVoucher.getSelectedRow();
        if (i == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn dòng cần sửa");
            return;
        }
       String maVoucher = txtmavoucher.getText().trim();
        String tenKM = txttenvoucher.getText().trim();
        String hinhThuc = cbbhinhthuc.getSelectedItem().toString();
        String soTienGiamstr = txtsotiengiam.getText().trim();
        String soptGiamstr = txtsoptgiam.getText().trim();
        Date ngaybd = Jdatengaybd.getDate();
        Date ngaykt = jdatengaykt.getDate();
        String dkGiam = txtdkgiam.getText().trim();
        String mucGiamToiDastr = txtmucgiamtoida.getText().trim();
        String trangThai;
        if (rdoconhieuluc.isSelected()) {
            trangThai = "Hoat Ðong";
        } else {
            trangThai = "Khong Hoat Đong";
        }
        if (maVoucher.isEmpty() || tenKM.isEmpty() || ngaybd == null || ngaykt == null ||dkGiam.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đủ thông tin");
            return;
        }
        float soTienGiam;
        try {
            soTienGiam = Float.parseFloat(soTienGiamstr);
            if (soTienGiam <0) {
                JOptionPane.showMessageDialog(this, "Số tiền giảm phải lớn hơn hoặc bằng 0");
                return;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập số tiền giảm là số nguyên");
            return;
        }
        int soptGiam;
        try {
            soptGiam = Integer.parseInt(soptGiamstr);
            if(soptGiam<0){
                JOptionPane.showMessageDialog(this, "Số tiền giảm phải lớn hơn hoặc bằng 0");
                return;
            }if(soptGiam>100){
                JOptionPane.showMessageDialog(this,"Số % giảm phải nhỏ hơn hoặc bằng 100");
                return;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập số % giảm là số nguyên");
            return;
        }
        if (ngaybd.after(ngaykt)) {
            JOptionPane.showMessageDialog(this, "Ngày kết thúc phải sau ngày bắt đầu");
            return;
        }
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String strNgayBatDau = sdf.format(ngaybd);
        String strNgayKetThuc = sdf.format(ngaykt);
        float mucGiamToiDa;
        try {
            mucGiamToiDa= Float.parseFloat(mucGiamToiDastr);
            if(mucGiamToiDa<=0){
                JOptionPane.showMessageDialog(this, "Vui lòng nhập mức giảm tối đa là số nguyên");
                return;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập mức giảm tối đa là số nguyên");
            return;
        }
        int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn sửa?", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION) {
            return; // User chose not to proceed
        }
        Model_Voucher mv = new Model_Voucher(maVoucher, tenKM, hinhThuc, soTienGiam, soptGiam, ngaybd, ngaykt, trangThai,dkGiam, mucGiamToiDa);
        this.repo_Voucher.sua(mv, maVoucher);
        this.fillTable(repo_Voucher.getAll());
        this.clearForm();
        JOptionPane.showMessageDialog(this, "Sửa thành công");


    }//GEN-LAST:event_btnsuaActionPerformed

    private void btnxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoaActionPerformed
        i = tblQLVoucher.getSelectedRow();
        if (i == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn dòng cần xóa");
            return;
        }
        String maVouchercx = txtmavoucher.getText().trim();
        int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa?", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION) {
            return; // User chose not to proceed
        }
        this.repo_Voucher.xoa(maVouchercx);
        this.fillTable(repo_Voucher.getAll());
        this.clearForm();
        JOptionPane.showMessageDialog(this, "Xóa Thành công");
    }//GEN-LAST:event_btnxoaActionPerformed

    private void tblQLVoucherMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblQLVoucherMouseClicked
        i = tblQLVoucher.getSelectedRow();
        this.showData(i);
    }//GEN-LAST:event_tblQLVoucherMouseClicked

    private void btntimkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntimkiemActionPerformed
        String maVoucherct = txttimkiem.getText().trim();
    String tenVct = txttimkiem.getText().trim();
    String trangThaict = txttimkiem.getText().trim();

    // Kiểm tra nếu ô tìm kiếm trống
    if (maVoucherct.isEmpty() && tenVct.isEmpty() && trangThaict.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Vui lòng nhập thông tin tìm kiếm.");
    } else {
        if (repo_Voucher.timkiem(maVoucherct, tenVct, trangThaict).isEmpty()) {
            JOptionPane.showMessageDialog(this, "Không tìm thấy danh sách.");
        } else {
            this.fillTable(repo_Voucher.timkiem(maVoucherct, tenVct, trangThaict));
            JOptionPane.showMessageDialog(this, "Danh sách được tìm thấy.");
        }
        txttimkiem.setText("");
    }

    }//GEN-LAST:event_btntimkiemActionPerformed

    private void txtmavoucherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmavoucherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmavoucherActionPerformed

    private void rdoconhieulucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoconhieulucActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoconhieulucActionPerformed

    private void btnlammoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlammoiActionPerformed
        this.clearForm();
    }//GEN-LAST:event_btnlammoiActionPerformed

    private void btnlammoitableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlammoitableActionPerformed
        this.fillTable(repo_Voucher.getAll());
    }//GEN-LAST:event_btnlammoitableActionPerformed

    private void cbbhinhthucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbhinhthucActionPerformed
        this.updateFieldsBasedOnComboBox();
    }//GEN-LAST:event_cbbhinhthucActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser Jdatengaybd;
    private javax.swing.JButton btnlammoi;
    private javax.swing.JButton btnlammoitable;
    private javax.swing.JButton btnsua;
    private javax.swing.JButton btnthem;
    private javax.swing.JButton btntimkiem;
    private javax.swing.JButton btnxoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbbhinhthuc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser jdatengaykt;
    private javax.swing.JRadioButton rdoconhieuluc;
    private javax.swing.JRadioButton rdohethieuluc;
    private javax.swing.JTable tblQLVoucher;
    private javax.swing.JTextField txtdkgiam;
    private javax.swing.JTextField txtmavoucher;
    private javax.swing.JTextField txtmucgiamtoida;
    private javax.swing.JTextField txtsoptgiam;
    private javax.swing.JTextField txtsotiengiam;
    private javax.swing.JTextField txttenvoucher;
    private javax.swing.JTextField txttimkiem;
    // End of variables declaration//GEN-END:variables
}
